function a = accel(G,m1,m2,m3,x1,x2,x3,y1,y2,y3)
%ACCEL
%    A = ACCEL(G,M1,M2,M3,X1,X2,X3,Y1,Y2,Y3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    12-Sep-2016 12:01:00

t4 = x1-x2;
t2 = abs(t4);
t5 = y1-y2;
t3 = abs(t5);
t8 = x1-x3;
t6 = abs(t8);
t9 = y1-y3;
t7 = abs(t9);
t10 = 1.0./m1;
t11 = t2.^2;
t12 = t3.^2;
t13 = t11+t12;
t14 = 1.0./sqrt(t13);
t15 = t4.^2;
t16 = t5.^2;
t17 = t15+t16;
t18 = 1.0./t17;
t19 = t6.^2;
t20 = t7.^2;
t21 = t19+t20;
t22 = 1.0./sqrt(t21);
t23 = t8.^2;
t24 = t9.^2;
t25 = t23+t24;
t26 = 1.0./t25;
t27 = G.*m1.*m2.*t4.*t14.*t18;
t30 = x2-x3;
t28 = abs(t30);
t31 = y2-y3;
t29 = abs(t31);
t32 = 1.0./m2;
t33 = G.*m1.*m2.*t5.*t14.*t18;
t34 = t28.^2;
t35 = t29.^2;
t36 = t34+t35;
t37 = 1.0./sqrt(t36);
t38 = t30.^2;
t39 = t31.^2;
t40 = t38+t39;
t41 = 1.0./t40;
t42 = G.*m1.*m3.*t8.*t22.*t26;
t43 = 1.0./m3;
t44 = G.*m1.*m3.*t9.*t22.*t26;
a = [-t10.*(t27+t42);-t10.*(t33+t44);t32.*(t27-G.*m2.*m3.*t30.*t37.*t41);t32.*(t33-G.*m2.*m3.*t31.*t37.*t41);t43.*(t42+G.*m2.*m3.*t30.*t37.*t41);t43.*(t44+G.*m2.*m3.*t31.*t37.*t41)];
