function angMom = angMom(in1,G,m1,m2,m3)
%ANGMOM
%    ANGMOM = ANGMOM(IN1,G,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Jun-2020 18:37:35

x1 = in1(:,1);
x2 = in1(:,3);
x3 = in1(:,5);
xdot1 = in1(:,7);
xdot2 = in1(:,9);
xdot3 = in1(:,11);
y1 = in1(:,2);
y2 = in1(:,4);
y3 = in1(:,6);
ydot1 = in1(:,8);
ydot2 = in1(:,10);
ydot3 = in1(:,12);
t2 = m1.*x1;
t3 = m2.*x2;
t4 = m3.*x3;
t5 = m1.*y1;
t6 = m2.*y2;
t7 = m3.*y3;
t8 = m1+m2+m3;
t9 = 1.0./t8;
t10 = t2+t3+t4;
t11 = t5+t6+t7;
t12 = t9.*t10;
t13 = t9.*t11;
t14 = -t12;
t15 = -t13;
angMom = -m1.*ydot1.*(t12-x1)+m1.*xdot1.*(t13-y1)-m2.*ydot2.*(t12-x2)+m2.*xdot2.*(t13-y2)-m3.*ydot3.*(t12-x3)+m3.*xdot3.*(t13-y3);
