function angMom = angMom(m1,m2,m3,x1,x2,x3,xdot1,xdot2,xdot3,y1,y2,y3,ydot1,ydot2,ydot3)
%ANGMOM
%    ANGMOM = ANGMOM(M1,M2,M3,X1,X2,X3,XDOT1,XDOT2,XDOT3,Y1,Y2,Y3,YDOT1,YDOT2,YDOT3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Jun-2020 08:22:19

t2 = m1.*x1;
t3 = m2.*x2;
t4 = m3.*x3;
t5 = m1.*y1;
t6 = m2.*y2;
t7 = m3.*y3;
t8 = m1+m2+m3;
t9 = 1.0./t8;
t10 = t2+t3+t4;
t11 = t5+t6+t7;
t12 = t9.*t10;
t13 = t9.*t11;
t14 = -t12;
t15 = -t13;
angMom = -m1.*ydot1.*(t12-x1)+m1.*xdot1.*(t13-y1)-m2.*ydot2.*(t12-x2)+m2.*xdot2.*(t13-y2)-m3.*ydot3.*(t12-x3)+m3.*xdot3.*(t13-y3);
