function potE = potE(in1,G,m1,m2,m3)
%POTE
%    POTE = POTE(IN1,G,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Jun-2020 08:22:27

x1 = in1(:,1);
x2 = in1(:,3);
x3 = in1(:,5);
y1 = in1(:,2);
y2 = in1(:,4);
y3 = in1(:,6);
t2 = -x3;
t3 = -y3;
potE = -G.*m1.*m2.*1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2)-G.*m1.*m3.*1.0./sqrt(abs(t2+x1).^2+abs(t3+y1).^2)-G.*m2.*m3.*1.0./sqrt(abs(t2+x2).^2+abs(t3+y2).^2);
