function totE = totE(in1,G,m1,m2,m3)
%TOTE
%    TOTE = TOTE(IN1,G,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Jun-2020 10:54:46

x1 = in1(:,1);
x2 = in1(:,3);
x3 = in1(:,5);
xdot1 = in1(:,7);
xdot2 = in1(:,9);
xdot3 = in1(:,11);
y1 = in1(:,2);
y2 = in1(:,4);
y3 = in1(:,6);
ydot1 = in1(:,8);
ydot2 = in1(:,10);
ydot3 = in1(:,12);
t2 = -x3;
t3 = -y3;
totE = (m1.*(xdot1.^2+ydot1.^2))./2.0+(m2.*(xdot2.^2+ydot2.^2))./2.0+(m2.*(xdot3.^2+ydot3.^2))./2.0-G.*m1.*m2.*1.0./sqrt(abs(x1-x2).^2+abs(y1-y2).^2)-G.*m1.*m3.*1.0./sqrt(abs(t2+x1).^2+abs(t3+y1).^2)-G.*m2.*m3.*1.0./sqrt(abs(t2+x2).^2+abs(t3+y2).^2);
