%% Problem 19 - Odd simple pendulum parameterization
% y - is horizontal right
% x - is vertical down
% Derive an ODE completely in y. Compare to ye olde standard 
% thdotdot = -g/l*sin(th);
%
% Note, our new EOM in y falls apart for negative x. Recall that a given y
% could correspond to two different angles. This manifests itself in the
% equations as square roots (which have +/- results).
%  
%   deriver.m does the symbolic derivation.\
%   RHS_derived.m is the RHS for the weird parameterization
%   RHS_simple.m is the RHS for the theta parameterization
%   ydotdot.m is an autogenerated expression for the acceleration of y
%   (used in RHS_derived.m and created by deriver.m)
%
% Matthew Sheen with Cameron Aubin
clear all; close all;

%% Parameters
p.m = 1;
p.l = 5;
p.g = 1;

%% Initial conditions
y_0 = -2;
ydot_0 = 1;

inits_derived = [y_0, ydot_0];
inits_simple = [asin(y_0/p.l), ydot_0/(sqrt(p.l^2-y_0^2))]; % Transform the y position and velocity into angles (think about the geometry awhile if you must)

%% Integrate
tvec = [0 50];
opts = odeset;
opts.RelTol = 1e-06;     
opts.AbsTol = 1e-06;

[tarray_derived, zarray_derived] = ode45(@RHS_derived,tvec,inits_derived,opts,p);
[tarray_simple, zarray_simple] = ode45(@RHS_simple,tvec,inits_simple,opts,p);

%% Plot
plot(tarray_derived, zarray_derived(:,1),'.',tarray_simple,sin(zarray_simple(:,1))*p.l,'-r','MarkerSize',10);
legend('Crazy derived','Simple equation')