function answer = ydotdot(g,l,y,ydot)
%YDOTDOT
%    ANSWER = YDOTDOT(G,L,Y,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Sep-2016 15:35:43

t2 = l.^2;
t3 = y.^2;
answer = (t2.*y.*ydot.^2+g.*y.*(t2-t3).^(3.0./2.0))./(t2.*t3-t2.^2);
