function phidot_inTime = phidot(t)
%PHIDOT
%    PHIDOT_INTIME = PHIDOT(T)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Sep-2016 14:56:08

t2 = cos(t);
t3 = t2.*pi;
t4 = cos(t3);
phidot_inTime = -(pi.*sin(t).*(t4.*2.0-1.0))./(t4.*4.0-9.0);
