function positions = positions(phi,t)
%POSITIONS
%    POSITIONS = POSITIONS(PHI,T)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Sep-2016 16:41:38

t2 = sin(phi);
t3 = cos(phi);
t4 = t3.*2.0;
t5 = cos(t);
t6 = t5-1.0;
t7 = t6.*pi;
t8 = sin(t7);
t9 = cos(t7);
t10 = t9+2.0;
t11 = t2.*t8;
t12 = t3.*t10;
t13 = t2.*t10;
positions = [t2.*-2.0,t4,t2.*2.0,-t4,t11+t12,t13-t3.*t8,-t11-t12,-t13+t3.*t8];
